-- MySQL Script generated by MySQL Workbench
-- 10/25/18 18:26:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projectrh
-- -----------------------------------------------------
-- Modelo projecto Nomina 4
-- 

-- -----------------------------------------------------
-- Table `tipoobj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipoobj` ;

CREATE TABLE IF NOT EXISTS `tipoobj` (
  `Gbukrs` VARCHAR(4) NOT NULL,
  `Bukrs` VARCHAR(4) NOT NULL,
  `TipoObjId` CHAR(10) NOT NULL,
  `Descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`TipoObjId`),
  INDEX `IDX_TIPO_OBJID` (`TipoObjId` ASC),
  INDEX `IDX_DESCRIPCION` (`Descripcion` ASC),
  INDEX `fk_tipoobj_cat11_idx` (`Gbukrs` ASC, `Bukrs` ASC),
  CONSTRAINT `fk_tipoobj_cat11`
    FOREIGN KEY (`Gbukrs` , `Bukrs`)
    REFERENCES `cat1` (`Gbukrs` , `Bukrs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `objetivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objetivo` ;

CREATE TABLE IF NOT EXISTS `objetivo` (
  `IdObjetivo` CHAR(10) NOT NULL,
  `TipoObjId` CHAR(10) NOT NULL,
  `Descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `Inicio` DATE NULL DEFAULT NULL,
  `Fin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IdObjetivo`),
  INDEX `IDX_Inicio` (`Inicio` ASC),
  INDEX `IDX_Fin` (`Fin` ASC),
  INDEX `IDX_DESC` (`Descripcion` ASC),
  INDEX `fk_objetivo_tipoobj1_idx` (`TipoObjId` ASC),
  CONSTRAINT `fk_objetivo_tipoobj1`
    FOREIGN KEY (`TipoObjId`)
    REFERENCES `tipoobj` (`TipoObjId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tareas` ;

CREATE TABLE IF NOT EXISTS `tareas` (
  `TareaId` CHAR(10) NOT NULL,
  `IdObjetivo` CHAR(10) NOT NULL,
  `TareasDesc` VARCHAR(2000) NULL,
  `TareasFechaRegistro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TareasFechaFinDeseado` DATE NULL,
  `TareasFechaFinReal` DATE NULL,
  PRIMARY KEY (`TareaId`),
  INDEX `idx_fecharegistro` (`TareasFechaRegistro` ASC),
  INDEX `idx_fechafin` (`TareasFechaFinDeseado` ASC),
  INDEX `idx_fechafinreal` (`TareasFechaFinReal` ASC),
  INDEX `fk_tareas_objetivo1_idx` (`IdObjetivo` ASC),
  INDEX `idx_tareasdesc` (`TareasDesc` ASC),
  CONSTRAINT `fk_tareas_objetivo1`
    FOREIGN KEY (`IdObjetivo`)
    REFERENCES `objetivo` (`IdObjetivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conocimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conocimientos` ;

CREATE TABLE IF NOT EXISTS `conocimientos` (
  `Id_Conocimientos` CHAR(10) NOT NULL,
  `Gburks` VARCHAR(4) NOT NULL,
  `Bukrs` VARCHAR(4) NOT NULL,
  `Conocimiento_Desc` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Conocimientos`, `Gburks`, `Bukrs`),
  INDEX `fk_conocimientos_cat11_idx` (`Gburks` ASC, `Bukrs` ASC),
  CONSTRAINT `fk_conocimientos_cat11`
    FOREIGN KEY (`Gburks` , `Bukrs`)
    REFERENCES `cat1` (`Gbukrs` , `Bukrs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `competencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `competencias` ;

CREATE TABLE IF NOT EXISTS `competencias` (
  `Id_Competencia` CHAR(10) NOT NULL,
  `Gbukrs` VARCHAR(4) NOT NULL,
  `Bukrs` VARCHAR(4) NOT NULL,
  `Competencias_Desc` VARCHAR(100) NOT NULL,
  `Generico` INT(8) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Competencia`, `Gbukrs`, `Bukrs`),
  INDEX `fk_competencias_cat11_idx` (`Gbukrs` ASC, `Bukrs` ASC),
  CONSTRAINT `fk_competencias_cat11`
    FOREIGN KEY (`Gbukrs` , `Bukrs`)
    REFERENCES `cat1` (`Gbukrs` , `Bukrs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacionpuestos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `evaluacionpuestos` ;

CREATE TABLE IF NOT EXISTS `evaluacionpuestos` (
  `IdEvaluacion` CHAR(10) NOT NULL,
  `Id_Conocimientos` CHAR(10) NOT NULL,
  `Gburks` VARCHAR(4) NOT NULL,
  `Bukrs` VARCHAR(4) NOT NULL,
  `Id_Competencia` CHAR(10) NOT NULL,
  PRIMARY KEY (`IdEvaluacion`),
  INDEX `FkCompetenciasEva_idx` (`Gburks` ASC, `Bukrs` ASC, `Id_Competencia` ASC),
  INDEX `FkCompetenciasCon_idx` (`Id_Conocimientos` ASC, `Gburks` ASC, `Bukrs` ASC),
  INDEX `FkCompetenciasCon2_idx` (`Id_Conocimientos` ASC, `Gburks` ASC, `Bukrs` ASC),
  CONSTRAINT `FKCompetenciasCon`
    FOREIGN KEY (`Id_Conocimientos` , `Gburks` , `Bukrs`)
    REFERENCES `conocimientos` (`Id_Conocimientos` , `Gburks` , `Bukrs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FkCompetenciasEva`
    FOREIGN KEY (`Gburks` , `Bukrs` , `Id_Competencia`)
    REFERENCES `competencias` (`Gbukrs` , `Bukrs` , `Id_Competencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tareaspersonal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tareaspersonal` ;

CREATE TABLE IF NOT EXISTS `tareaspersonal` (
  `TareaId` CHAR(10) NOT NULL,
  `PERNR` CHAR(10) NOT NULL,
  `Observaciones` VARCHAR(2000) NULL,
  `FRegistro` DATETIME NULL,
  `PorcAvance` DECIMAL(5,2) NULL,
  PRIMARY KEY (`TareaId`, `PERNR`),
  INDEX `fk_tareaspesonal_tareas1_idx` (`TareaId` ASC),
  CONSTRAINT `fk_tareaspesonal_tareas1`
    FOREIGN KEY (`TareaId`)
    REFERENCES `tareas` (`TareaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
